import React, { useState } from 'react';
import { Eye, Edit3, Sparkles, AlertCircle, CheckCircle, Image as ImageIcon, Grid, Download } from 'lucide-react';
import { AnalysisResult } from '../types';

interface ComparisonViewProps {
  result: AnalysisResult;
}

type ViewMode = 'original' | 'overlay' | 'structure' | 'fixed';

export const ComparisonView: React.FC<ComparisonViewProps> = ({ result }) => {
  const [viewMode, setViewMode] = useState<ViewMode>('structure');

  // Convert base64 to usable src
  const originalSrc = `data:image/jpeg;base64,${result.originalImage}`;
  const overlaySrc = result.overlayImage ? `data:image/png;base64,${result.overlayImage}` : null;
  const structureSrc = result.structureImage ? `data:image/png;base64,${result.structureImage}` : null;
  const fixedSrc = result.fixedImage ? `data:image/png;base64,${result.fixedImage}` : null;

  // Determine what to show
  let currentImageSrc = originalSrc;
  if (viewMode === 'overlay' && overlaySrc) currentImageSrc = overlaySrc;
  if (viewMode === 'structure' && structureSrc) currentImageSrc = structureSrc;
  if (viewMode === 'fixed' && fixedSrc) currentImageSrc = fixedSrc;

  // Safe fallback
  if (!currentImageSrc) currentImageSrc = originalSrc;

  const handleDownloadReport = () => {
    const reportContent = `
# Art Analysis Report
Generated by ArtLint (Gemini Powered)

## Critique
${result.textCritique}

## Key Observations
${result.points.map(p => `- [${p.severity.toUpperCase()}] **${p.title}**: ${p.description}`).join('\n')}

## Recommended Exercises
${result.suggestedExercises.map(e => `- ${e}`).join('\n')}

---
*Report generated on ${new Date().toLocaleDateString()}*
    `;

    const blob = new Blob([reportContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'artlint-critique.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-6xl mx-auto p-4 space-y-8 animate-fade-in">
      
      {/* Main Image View Area */}
      <div className="bg-gray-800 rounded-2xl p-1 shadow-2xl border border-gray-700 flex flex-col">
        {/* Toolbar */}
        <div className="flex flex-col xl:flex-row xl:items-center justify-between p-4 bg-gray-850 rounded-t-xl border-b border-gray-700 gap-4">
            <h2 className="text-lg font-semibold text-gray-200 flex items-center">
                <Eye className="w-5 h-5 mr-2 text-indigo-400"/> Studio View
            </h2>

            <div className="flex bg-gray-900 rounded-lg p-1 border border-gray-700 overflow-x-auto">
                <button 
                    onClick={() => setViewMode('original')}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'original' 
                        ? 'bg-gray-700 text-white shadow-sm' 
                        : 'text-gray-400 hover:text-white'
                    }`}
                >
                    <ImageIcon className="w-4 h-4 mr-2" />
                    Original
                </button>
                <button 
                    onClick={() => setViewMode('overlay')}
                    disabled={!overlaySrc}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'overlay' 
                        ? 'bg-indigo-600 text-white shadow-sm' 
                        : 'text-gray-400 hover:text-white disabled:opacity-50 disabled:cursor-not-allowed'
                    }`}
                >
                    <Edit3 className="w-4 h-4 mr-2" />
                    Corrections
                </button>
                 <button 
                    onClick={() => setViewMode('structure')}
                    disabled={!structureSrc}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'structure' 
                        ? 'bg-blue-600 text-white shadow-sm' 
                        : 'text-gray-400 hover:text-white disabled:opacity-50 disabled:cursor-not-allowed'
                    }`}
                >
                    <Grid className="w-4 h-4 mr-2" />
                    Structure Guide
                </button>
                <button 
                    onClick={() => setViewMode('fixed')}
                    disabled={!fixedSrc}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'fixed' 
                        ? 'bg-purple-600 text-white shadow-sm' 
                        : 'text-gray-400 hover:text-white disabled:opacity-50 disabled:cursor-not-allowed'
                    }`}
                >
                    <Sparkles className="w-4 h-4 mr-2" />
                    Polished
                </button>
            </div>
        </div>

        {/* Image Container */}
        <div className="relative w-full min-h-[400px] md:min-h-[600px] bg-gray-900 rounded-b-xl overflow-hidden flex items-center justify-center p-4">
             {/* Pattern background to show transparency if applicable */}
            <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(#4b5563 1px, transparent 1px)', backgroundSize: '20px 20px' }}></div>
            
            <img 
                src={currentImageSrc} 
                alt="Art Analysis" 
                className="relative max-w-full max-h-[80vh] object-contain rounded-lg shadow-lg transition-opacity duration-300"
            />

            {/* Description overlay for current mode */}
            <div className="absolute top-4 left-4 z-10 pointer-events-none">
                 <div className="bg-black/60 backdrop-blur text-white text-xs px-3 py-1.5 rounded-full border border-white/10 shadow-lg">
                    {viewMode === 'original' && "Your Original Drawing"}
                    {viewMode === 'overlay' && "Teacher's Corrections (Red Lines)"}
                    {viewMode === 'structure' && "Geometric Breakdown & Construction"}
                    {viewMode === 'fixed' && "Final Polished Version"}
                 </div>
            </div>

            {/* Hold to Compare overlay (Only on Fixed/Overlay modes) */}
            {viewMode !== 'original' && (
                <div 
                    className="absolute bottom-6 right-6 z-10"
                >
                   <button 
                    className="bg-black/60 hover:bg-black/80 backdrop-blur text-white text-xs px-3 py-2 rounded-full border border-white/20 select-none active:scale-95 transition-transform"
                    onMouseDown={(e) => {
                         const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                         if(img) img.src = originalSrc;
                    }}
                    onMouseUp={(e) => {
                        const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                        if(img) img.src = currentImageSrc;
                    }}
                    onMouseLeave={(e) => {
                        const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                        if(img) img.src = currentImageSrc;
                    }}
                    onTouchStart={(e) => {
                         const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                         if(img) img.src = originalSrc;
                    }}
                    onTouchEnd={(e) => {
                        const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                        if(img) img.src = currentImageSrc;
                    }}
                   >
                    Hold to View Original
                   </button>
                </div>
            )}
        </div>
      </div>

      {/* Text Critique Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Main Critique */}
        <div className="lg:col-span-2 space-y-6">
            <div className="flex justify-between items-center">
                 <h3 className="text-xl font-bold text-white">Teacher's Critique</h3>
                 <button 
                    onClick={handleDownloadReport}
                    className="flex items-center text-sm text-indigo-400 hover:text-indigo-300 transition-colors"
                 >
                    <Download className="w-4 h-4 mr-2" /> Download Report (.md)
                 </button>
            </div>
            
            <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">
                <p className="text-gray-300 leading-relaxed text-lg">
                    {result.textCritique}
                </p>
            </div>

            <div className="bg-gray-800 rounded-2xl p-6 border border-gray-700">
                <h3 className="text-xl font-bold text-white mb-4">Detailed Analysis</h3>
                <div className="space-y-4">
                    {result.points.map((point, index) => (
                        <div key={index} className="flex items-start p-4 bg-gray-900/50 rounded-xl border border-gray-800">
                            <div className={`mt-1 mr-4 flex-shrink-0 ${
                                point.severity === 'high' ? 'text-red-500' : 
                                point.severity === 'medium' ? 'text-yellow-500' : 'text-blue-500'
                            }`}>
                                <AlertCircle size={24} />
                            </div>
                            <div>
                                <h4 className="font-semibold text-gray-200">{point.title}</h4>
                                <p className="text-sm text-gray-400 mt-1">{point.description}</p>
                            </div>
                            <span className={`ml-auto text-xs font-bold px-2 py-1 rounded uppercase ${
                                 point.severity === 'high' ? 'bg-red-500/20 text-red-400' : 
                                 point.severity === 'medium' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-blue-500/20 text-blue-400'
                            }`}>
                                {point.severity}
                            </span>
                        </div>
                    ))}
                </div>
            </div>
        </div>

        {/* Exercises Sidebar */}
        <div className="lg:col-span-1">
            <div className="bg-gradient-to-br from-indigo-900 to-gray-900 rounded-2xl p-6 border border-indigo-500/30 sticky top-24">
                <h3 className="text-xl font-bold text-white mb-6 flex items-center">
                    <CheckCircle className="w-5 h-5 mr-2 text-green-400" />
                    Recommended Training
                </h3>
                <ul className="space-y-4">
                    {result.suggestedExercises.map((ex, i) => (
                        <li key={i} className="flex">
                            <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-full bg-indigo-500/20 text-indigo-400 text-xs font-bold mr-3 border border-indigo-500/30">
                                {i + 1}
                            </span>
                            <span className="text-gray-300 text-sm">{ex}</span>
                        </li>
                    ))}
                </ul>
                
                <div className="mt-8 pt-6 border-t border-gray-700">
                    <button className="w-full py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium transition-colors text-sm">
                        Find Lessons for These Topics
                    </button>
                </div>
            </div>
        </div>

      </div>
    </div>
  );
};