import React, { useState } from 'react';
import { Eye, Edit3, Sparkles, AlertCircle, CheckCircle, Image as ImageIcon, Grid, Download, BookOpen, Loader2 } from 'lucide-react';
import { AnalysisResult } from '../types';

interface ComparisonViewProps {
  result: AnalysisResult;
  onGenerateLesson: () => void;
  isGeneratingLesson: boolean;
}

type ViewMode = 'original' | 'overlay' | 'structure' | 'fixed';

export const ComparisonView: React.FC<ComparisonViewProps> = ({ result, onGenerateLesson, isGeneratingLesson }) => {
  const [viewMode, setViewMode] = useState<ViewMode>('structure');

  // Convert base64 to usable src
  const originalSrc = `data:image/jpeg;base64,${result.originalImage}`;
  const overlaySrc = result.overlayImage ? `data:image/png;base64,${result.overlayImage}` : null;
  const structureSrc = result.structureImage ? `data:image/png;base64,${result.structureImage}` : null;
  const fixedSrc = result.fixedImage ? `data:image/png;base64,${result.fixedImage}` : null;

  // Determine what to show
  let currentImageSrc = originalSrc;
  if (viewMode === 'overlay' && overlaySrc) currentImageSrc = overlaySrc;
  if (viewMode === 'structure' && structureSrc) currentImageSrc = structureSrc;
  if (viewMode === 'fixed' && fixedSrc) currentImageSrc = fixedSrc;

  // Safe fallback
  if (!currentImageSrc) currentImageSrc = originalSrc;

  // Score color logic
  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-emerald-400 border-emerald-500/30';
    if (score >= 70) return 'text-sky-400 border-sky-500/30';
    if (score >= 50) return 'text-amber-400 border-amber-500/30';
    return 'text-red-400 border-red-500/30';
  };

  const scoreColor = getScoreColor(result.score || 0);

  const handleDownloadReport = () => {
    const reportContent = `
# Art Analysis Report
Generated by ArtLint (Gemini Powered)
Score: ${result.score}/100

## Critique
${result.textCritique}

## Key Observations
${result.points.map(p => `- [${p.severity.toUpperCase()}] **${p.title}**: ${p.description}`).join('\n')}

## Recommended Exercises
${result.suggestedExercises.map(e => `- ${e}`).join('\n')}

---
*Report generated on ${new Date().toLocaleDateString()}*
    `;

    const blob = new Blob([reportContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'artlint-critique.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-6xl mx-auto p-4 space-y-8 animate-fade-in">
      
      {/* Main Image View Area */}
      <div className="bg-stone-900 rounded-xl p-1 shadow-2xl border border-stone-800 flex flex-col">
        {/* Toolbar */}
        <div className="flex flex-col xl:flex-row xl:items-center justify-between p-4 bg-stone-900 rounded-t-xl border-b border-stone-800 gap-4">
            <div className="flex items-center gap-4">
                 <h2 className="text-lg font-bold text-stone-200 flex items-center font-serif">
                    <Eye className="w-5 h-5 mr-2 text-sky-400"/> Studio View
                </h2>
                {result.score !== undefined && (
                    <div className={`px-3 py-1 rounded-full border bg-stone-950 font-bold font-mono text-sm ${scoreColor}`}>
                        Score: {result.score}
                    </div>
                )}
            </div>

            <div className="flex bg-stone-950 rounded-lg p-1 border border-stone-800 overflow-x-auto">
                <button 
                    onClick={() => setViewMode('original')}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'original' 
                        ? 'bg-stone-800 text-white shadow-sm' 
                        : 'text-stone-500 hover:text-stone-300'
                    }`}
                >
                    <ImageIcon className="w-4 h-4 mr-2" />
                    Original
                </button>
                <button 
                    onClick={() => setViewMode('overlay')}
                    disabled={!overlaySrc}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'overlay' 
                        ? 'bg-red-900/50 text-red-200 border border-red-900 shadow-sm' 
                        : 'text-stone-500 hover:text-stone-300 disabled:opacity-50 disabled:cursor-not-allowed'
                    }`}
                >
                    <Edit3 className="w-4 h-4 mr-2" />
                    Corrections
                </button>
                 <button 
                    onClick={() => setViewMode('structure')}
                    disabled={!structureSrc}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'structure' 
                        ? 'bg-sky-900/50 text-sky-200 border border-sky-900 shadow-sm' 
                        : 'text-stone-500 hover:text-stone-300 disabled:opacity-50 disabled:cursor-not-allowed'
                    }`}
                >
                    <Grid className="w-4 h-4 mr-2" />
                    Structure
                </button>
                <button 
                    onClick={() => setViewMode('fixed')}
                    disabled={!fixedSrc}
                    className={`flex items-center px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${
                        viewMode === 'fixed' 
                        ? 'bg-purple-900/50 text-purple-200 border border-purple-900 shadow-sm' 
                        : 'text-stone-500 hover:text-stone-300 disabled:opacity-50 disabled:cursor-not-allowed'
                    }`}
                >
                    <Sparkles className="w-4 h-4 mr-2" />
                    Polished
                </button>
            </div>
        </div>

        {/* Image Container */}
        <div className="relative w-full min-h-[400px] md:min-h-[600px] bg-stone-950 rounded-b-lg overflow-hidden flex items-center justify-center p-8">
             {/* Pattern background */}
            <div className="absolute inset-0 opacity-[0.03]" style={{ backgroundImage: 'radial-gradient(#ffffff 1px, transparent 1px)', backgroundSize: '24px 24px' }}></div>
            
            <div className="relative p-2 bg-white rounded-sm shadow-2xl">
                <img 
                    src={currentImageSrc} 
                    alt="Art Analysis" 
                    className="relative max-w-full max-h-[75vh] object-contain"
                />
            </div>

            {/* Description overlay */}
            <div className="absolute top-4 left-4 z-10 pointer-events-none">
                 <div className="bg-stone-900/80 backdrop-blur text-stone-200 text-xs px-3 py-1.5 rounded-full border border-stone-700 shadow-lg font-medium">
                    {viewMode === 'original' && "Your Original Drawing"}
                    {viewMode === 'overlay' && "Teacher's Corrections (Red Lines)"}
                    {viewMode === 'structure' && "Geometric Breakdown & Construction"}
                    {viewMode === 'fixed' && "Final Polished Version"}
                 </div>
            </div>

            {/* Hold to Compare overlay */}
            {viewMode !== 'original' && (
                <div 
                    className="absolute bottom-6 right-6 z-10"
                >
                   <button 
                    className="bg-stone-900/80 hover:bg-stone-800 backdrop-blur text-stone-200 text-xs px-4 py-2 rounded-full border border-stone-700 select-none active:scale-95 transition-transform font-bold"
                    onMouseDown={(e) => {
                         const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                         if(img) img.src = originalSrc;
                    }}
                    onMouseUp={(e) => {
                        const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                        if(img) img.src = currentImageSrc;
                    }}
                    onMouseLeave={(e) => {
                        const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                        if(img) img.src = currentImageSrc;
                    }}
                    onTouchStart={(e) => {
                         const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                         if(img) img.src = originalSrc;
                    }}
                    onTouchEnd={(e) => {
                        const img = e.currentTarget.parentElement?.parentElement?.querySelector('img');
                        if(img) img.src = currentImageSrc;
                    }}
                   >
                    Hold to View Original
                   </button>
                </div>
            )}
        </div>
      </div>

      {/* Text Critique Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Main Critique */}
        <div className="lg:col-span-2 space-y-6">
            <div className="flex justify-between items-center">
                 <h3 className="text-2xl font-bold text-stone-100 font-serif">Teacher's Critique</h3>
                 <button 
                    onClick={handleDownloadReport}
                    className="flex items-center text-sm text-sky-400 hover:text-sky-300 transition-colors font-medium"
                 >
                    <Download className="w-4 h-4 mr-2" /> Download Report
                 </button>
            </div>
            
            <div className="bg-stone-900 rounded-xl p-8 border border-stone-800 shadow-sm">
                <p className="text-stone-300 leading-8 text-lg font-light font-serif">
                    "{result.textCritique}"
                </p>
            </div>

            <div className="bg-stone-900 rounded-xl p-8 border border-stone-800 shadow-sm">
                <h3 className="text-xl font-bold text-stone-100 mb-6 font-serif">Detailed Observations</h3>
                <div className="space-y-4">
                    {result.points.map((point, index) => (
                        <div key={index} className="flex items-start p-4 bg-stone-950/50 rounded-lg border border-stone-800">
                            <div className={`mt-1 mr-4 flex-shrink-0 ${
                                point.severity === 'high' ? 'text-red-400' : 
                                point.severity === 'medium' ? 'text-amber-400' : 'text-sky-400'
                            }`}>
                                <AlertCircle size={20} />
                            </div>
                            <div className="flex-1">
                                <h4 className="font-bold text-stone-200 text-sm mb-1">{point.title}</h4>
                                <p className="text-sm text-stone-400 leading-relaxed">{point.description}</p>
                            </div>
                            <span className={`ml-4 text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider ${
                                 point.severity === 'high' ? 'bg-red-900/30 text-red-300 border border-red-900' : 
                                 point.severity === 'medium' ? 'bg-amber-900/30 text-amber-300 border border-amber-900' : 'bg-sky-900/30 text-sky-300 border border-sky-900'
                            }`}>
                                {point.severity}
                            </span>
                        </div>
                    ))}
                </div>
            </div>
        </div>

        {/* Exercises Sidebar */}
        <div className="lg:col-span-1">
            <div className="bg-stone-900 rounded-xl p-6 border border-stone-800 sticky top-24 shadow-lg">
                <h3 className="text-lg font-bold text-stone-100 mb-6 flex items-center font-serif">
                    <CheckCircle className="w-5 h-5 mr-2 text-emerald-500" />
                    Recommended Practice
                </h3>
                <ul className="space-y-6">
                    {result.suggestedExercises.map((ex, i) => (
                        <li key={i} className="flex items-start">
                            <span className="flex-shrink-0 w-6 h-6 flex items-center justify-center rounded-full bg-stone-800 text-stone-400 text-xs font-bold mr-3 border border-stone-700 mt-0.5 font-mono">
                                {i + 1}
                            </span>
                            <span className="text-stone-300 text-sm leading-relaxed">{ex}</span>
                        </li>
                    ))}
                </ul>
                
                <div className="mt-8 pt-6 border-t border-stone-800">
                     <button 
                        onClick={onGenerateLesson}
                        disabled={isGeneratingLesson}
                        className="w-full py-4 bg-gradient-to-r from-sky-600 to-indigo-600 hover:from-sky-500 hover:to-indigo-500 text-white rounded-lg font-bold transition-all text-sm shadow-md flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed group"
                    >
                        {isGeneratingLesson ? (
                            <>
                                <Loader2 className="w-4 h-4 mr-2 animate-spin" /> Generating...
                            </>
                        ) : (
                            <>
                                <BookOpen className="w-4 h-4 mr-2 group-hover:scale-110 transition-transform" /> Generate Personal Lesson
                            </>
                        )}
                    </button>
                    <p className="text-xs text-stone-500 mt-3 text-center">Experimental: AI creates a custom lesson based on your mistakes.</p>
                </div>
            </div>
        </div>

      </div>
    </div>
  );
};
